# Generated by Django 3.1.2 on 2021-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210128_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Electronic', 'Electronic'), ('Book', 'Book')], max_length=10, null=True),
        ),
    ]
